// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opnmdddqushvzxjqjgbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wbm1kZGRxdXNodnp4anFqZ2J2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzMyMTgsImV4cCI6MjA3MTk0OTIxOH0.amGKGH6gpA1ZClz3cFY7LzvF2IPqkK38EOa4zFzZwB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});